### ISSUE TITLE
License

### ISSUE THREAD

**Issue by LinusU** [bjornsallarp/Mitt-Saldo-Library#1]
Hi,

I noticed that your library doesn't have a license and thus cannot be used in any projects. It would be great if you could add a license so that we may use this library in lots of creative ways. I would suggest the MIT license, but have a look at this website and decide how you want it to be used.

http://choosealicense.com/

**Comment by bjornsallarp** [comment]
Says in pretty much every file:

//  Created by Björn Sållarp
//  NO Copyright. NO rights reserved.
//
//  Use this code any way you like. If you do like it, please
//  link to my blog and/or write a friendly comment. Thank you!

No license. Go bananas!

**Comment by LinusU** [comment]
Ahh, cool!
